load("@build_bazel_rules_swift//swift:swift.bzl",
    "swift_test"
)

swift_test(
    name = "NeedleFoundationTestTests",
    deps = [
        "//Sources/NeedleFoundationTest:NeedleFoundationTest"
    ],
    srcs = [
        "MockComponentPathBuilderTests.swift"
    ]
)
